name = "lms-backend"
main = "src/index.ts"
compatibility_date = "2026-03-09"
compatibility_flags = [ "nodejs_compat" ]

[vars]
POSTHOG_HOST = "https://us.i.posthog.com"
JWT_SECRET = "local-dev-super-secret-key-change-me"

[[r2_buckets]]
binding = "LMS_UPLOADS"
bucket_name = "lms-uploads"

[[queues.producers]]
binding = "LMS_QUEUE"
queue = "lms-events"

[[queues.consumers]]
queue = "lms-events"
dead_letter_queue = "lms-events-dlq"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
